name: Docker Image deploy

on: 
  push:
    branches:
    - "main"

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/multiplatform-test:latest